groups:
- name: docker-images-environment
  jobs:
  - build-fission-python-test-image
  - build-fission-go-env-image
  - build-fission-go-builder-image
  - build-fission-nodejs-env-image
  - build-fission-binary-env-image
- name: docker-images-test
  jobs: 
  - build-fission-python-env-image
  - build-fission-go-test-image
  - build-fission-nodejs-test-image
  - build-fission-binary-test-image
- name: fission-functions
  jobs:
  - fission-python-echo
  - fission-nodejs-form-to-json
  - fission-go-form-req-processor
- name: python-pipeline
  jobs: 
  - build-fission-python-test-image
  - build-fission-python-env-image
  - fission-python-echo
- name: nodejs-pipeline
  jobs: 
  - build-fission-nodejs-test-image
  - build-fission-nodejs-env-image
  - fission-nodejs-form-to-json
- name: go-pipeline
  jobs: 
  - build-fission-go-test-image
  - build-fission-go-env-image
  - build-fission-go-builder-image
  - fission-go-form-req-processor

resource_types:
# https://github.com/cloudfoundry-community/slack-notification-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: src
  type: git
  source:
    uri: https://github.com/OpenIndustryCloud/OIC-Platform.git
    branch: master
    disable_ci_skip: true
- name: go-functions-amit
  type: git
  source:
    uri: https://github.com/AmitKrVarman/fission-functions.git
    branch: tests
    disable_ci_skip: true
- name: slack-alert-infra
  type: slack-notification
  source:
    url: ((slack-url))
- name: docker-image-python-test
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-python-env))
    tag: test
- name: docker-image-python-env
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-python-env))
    tag: latest
- name: docker-image-go-test
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-go-env))
    tag: test
- name: docker-image-go-env
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-go-env))
    tag: latest
- name: docker-image-go-builder
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-go-builder))
    tag: latest
- name: docker-image-nodejs-test
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-nodejs-env))
    tag: test
- name: docker-image-nodejs-env
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-nodejs-env))
    tag: latest
- name: docker-image-binary-test
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-binary-env))
    tag: test
- name: docker-image-binary-env
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-binary-env))
    tag: latest


jobs:  
# Update Python Images
- name: build-fission-python-env-image
  public: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/python3"    
  - put: docker-image-python-env
    params:
      build: src/src/docker-images/fission/environments/python3
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We tested, built and published a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          Sorry, we failed to publish a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID


- name: build-fission-python-test-image
  public: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/python3/test"    
  - put: docker-image-python-test
    params:
      build: src/src/docker-images/fission/environments/python3
      dockerfile: src/src/docker-images/fission/environments/python3/test/Dockerfile
      tag: src/src/docker-images/fission/environments/python3/test/tag
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We tested, built and published a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          Sorry, we failed to publish a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID


# Update Go images
- name: build-fission-go-env-image
  public: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/go"    
  - put: docker-image-go-env
    params:
      build: src/src/docker-images/fission/environments/go
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We tested, built and published a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          Sorry, we failed to publish a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID


- name: build-fission-go-builder-image
  public: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/go/builder"    
  - put: docker-image-go-builder
    params:
      build: src/src/docker-images/fission/environments/go/builder
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We tested, built and published a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          Sorry, we failed to publish a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID


- name: build-fission-go-test-image
  public: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/go/test"    
  - put: docker-image-go-test
    params:
      build: src/src/docker-images/fission/environments/go
      dockerfile: src/src/docker-images/fission/environments/go/test/Dockerfile
      tag: src/src/docker-images/fission/environments/go/test/tag
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We tested, built and published a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          Sorry, we failed to publish a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID


# Update nodejs images
- name: build-fission-nodejs-env-image
  public: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/nodejs"    
  - put: docker-image-nodejs-env
    params:
      build: src/src/docker-images/fission/environments/nodejs
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We tested, built and published a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          Sorry, we failed to publish a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID


- name: build-fission-nodejs-test-image
  public: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/nodejs/test"    
  - put: docker-image-nodejs-test
    params:
      build: src/src/docker-images/fission/environments/nodejs
      dockerfile: src/src/docker-images/fission/environments/nodejs/test/Dockerfile
      tag: src/src/docker-images/fission/environments/nodejs/test/tag
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We tested, built and published a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          Sorry, we failed to publish a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID


# Update Binary Image
- name: build-fission-binary-env-image
  public: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/binary"    
  - put: docker-image-binary-env
    params:
      build: src/src/docker-images/fission/environments/binary
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We tested, built and published a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          Sorry, we failed to publish a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID


- name: build-fission-binary-test-image
  public: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/binary/test"    
  - put: docker-image-binary-test
    params:
      build: src/src/docker-images/fission/environments/binary
      dockerfile: src/src/docker-images/fission/environments/binary/test/Dockerfile
      tag: src/src/docker-images/fission/environments/binary/test/tag
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We tested, built and published a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          Sorry, we failed to publish a new Docker image for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID

####
#
# Fission functions tested after the images are published
#
####

# Python Functions
- name: fission-python-echo
  public: true
  plan:
  - aggregate:   
    - get: src
      trigger: true
    - get: docker-image-python-test
      passed: [ build-fission-python-test-image ]
  - task: lint-python
    file: src/ci/python/lint/lint_python.yaml
  - task: newman-function
    image: docker-image-python-test
    file: src/ci/python/function/test_function.yaml
    input_mapping: {src: src}
    params:
      FUNCTION_PATH: "src/workflows/fission/echo"
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We successfully tested a function for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          WARNING Tests do not pass on a function. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID


# Nodejs Functions
- name: fission-nodejs-form-to-json
  public: true
  serial: true
  plan:
  - aggregate:   
    - get: src
      trigger: true
    - get: docker-image-nodejs-test
      passed: [ build-fission-nodejs-test-image ]
  - task: newman-function
    image: docker-image-nodejs-test
    file: src/ci/nodejs/function/test_function.yaml
    input_mapping: {src: src}
    params:
      FUNCTION_PATH: "src/workflows/fission/form_to_json"
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We successfully tested a function for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          WARNING Tests do not pass on a function. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID

# Go Functions
- name: fission-go-form-req-processor
  public: true
  serial: true
  plan:
  - aggregate:   
    - get: docker-image-go-test
      passed: [ build-fission-go-test-image ]
  - get: go-functions-amit
    trigger: true
  - task: newman-function
    image: docker-image-go-test
    file: go-functions-amit/examples-go/form-req-processor/ci/test_function.yaml
    input_mapping: 
      src: go-functions-amit
    params:
      FUNCTION_PATH: "examples-go/form-req-processor"
    on_success: 
      put: slack-alert-infra
      params:
        text: |
          We successfully tested a function for the infrastructure. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID
    on_failure: 
      put: slack-alert-infra
      params:
        text: |
          WARNING Tests do not pass on a function. See at: 
          https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
          or at:
          https://concourse.((domain))/builds/$BUILD_ID

