resource_types:
# https://github.com/cloudfoundry-community/slack-notification-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: src
  type: git
  source:
    uri: https://github.com/OpenIndustryCloud/OIC-Platform.git
    branch: master
    disable_ci_skip: true
- name: slack-alert-infra
  type: slack-notification
  source:
    url: ((slack-url))
- name: docker-image-python-test
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-python-env))
    tag: test
- name: docker-image-python-env
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-python-env))
    tag: latest
- name: docker-image-go-test
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-go-env))
    tag: test
- name: docker-image-go-env
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-go-env))
    tag: latest
- name: docker-image-nodejs-test
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-nodejs-env))
    tag: test
- name: docker-image-nodejs-env
  type: docker-image
  source:
    email: ((docker-gcr-email))
    username: ((docker-gcr-username))
    password: ((docker-gcr-password))
    repository: ((docker-gcr-root))/((docker-image-nodejs-env))
    tag: latest



jobs:  
# Update Python Images
- name: build-fission-python-env-image
  public: true
  serial: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/python3"    
  - put: docker-image-python-env
    params:
      build: src/src/docker-images/fission/environments/python3
      tag: latest

- name: build-fission-python-test-image
  public: true
  serial: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/python3/test"    
  - put: docker-image-python-test
    params:
      build: src/src/docker-images/fission/environments/python3
      dockerfile: src/src/docker-images/fission/environments/python3/test/Dockerfile
      tag: src/src/docker-images/fission/environments/python3/test/tag
  - put: slack-alert-infra
    params:
      text: |
        We tested and built several Docker images for the infrastructure. See at: 
        https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        or at:
        https://concourse.((domain))/builds/$BUILD_ID

# Update Go images
- name: build-fission-go-env-image
  public: true
  serial: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/go"    
  - put: docker-image-go-env
    params:
      build: src/src/docker-images/fission/environments/go
      tag: latest

- name: build-fission-go-test-image
  public: true
  serial: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/go/test"    
  - put: docker-image-go-test
    params:
      build: src/src/docker-images/fission/environments/go
      dockerfile: src/src/docker-images/fission/environments/go/test/Dockerfile
      tag: src/src/docker-images/fission/environments/go/test/tag
  - put: slack-alert-infra
    params:
      text: |
        We tested and built several Docker images for the infrastructure. See at: 
        https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        or at:
        https://concourse.((domain))/builds/$BUILD_ID

# Update nodejs images
- name: build-fission-nodejs-env-image
  public: true
  serial: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/nodejs"    
  - put: docker-image-nodejs-env
    params:
      build: src/src/docker-images/fission/environments/nodejs
      tag: latest

- name: build-fission-python-test-image
  public: true
  serial: true
  plan:
  - get: src
    trigger: true
  - task: lint-dockerfiles
    file: src/ci/docker/lint/lint_dockerfile.yaml
    params: 
      SEARCH_PATH: "src/src/docker-images/fission/environments/nodejs/test"    
  - put: docker-image-python-test
    params:
      build: src/src/docker-images/fission/environments/nodejs
      dockerfile: src/src/docker-images/fission/environments/nodejs/test/Dockerfile
      tag: src/src/docker-images/fission/environments/nodejs/test/tag
  - put: slack-alert-infra
    params:
      text: |
        We tested and built several Docker images for the infrastructure. See at: 
        https://concourse.((domain))/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        or at:
        https://concourse.((domain))/builds/$BUILD_ID


