groups:
- name: main
  jobs:
  - unit-tests
  - deploy-app
  - load-tests
  - promote-new-version

resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: repo-pva
  type: git
  source:
    # uri: https://github.com/AmitKrVarman/PolicyValidationAPI
    uri: https://github.com/SaMnCo/demo-app
    branch: master
    disable_ci_skip: true
- name: every-30m
  type: time
  source: {interval: 30m}
- name: every-60m
  type: time
  source: {interval: 60m}
  # - name: myapp-helm
#   type: helm
#   source:
#     cluster_url: https://kube-master.domain.example
#     cluster_ca: _base64 encoded CA pem_
#     admin_key: _base64 encoded key pem_
#     admin_cert: _base64 encoded certificate pem_
#     repos:
#       - name: some_repo
#         url: https://somerepo.github.io/charts
- name: slack-alert-infra
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

jobs:
- name: unit-tests
  plan:
  - get: every-30m
    trigger: true
  - get: repo-pva
  - task: say-building
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Building application Policy Validation API"]
  - put: slack-alert-infra
    params:
      # channel: '#infrastructure'
      # text_file: results/message.txt
      text: |
        The build had a result. Check it out at:
        http://http://35.197.253.8:8080/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
        or at:
        http://my.concourse.url/builds/$BUILD_ID

        Result: $TEXT_FILE_CONTENT    

- name: deployment
  plan:
  - get: every-60m
    trigger: true
  - task: say-deploying
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["Deploying Policy Validation API"]
  - put: slack-alert-infra
    params:
      # channel: '#infrastructure'
      # text_file: results/message.txt
      text: |
        We are deploying Policy Validation API to staging 



